Add JavaScript DOM insertion to enable menu bar open/close functionality
Nessrine88/Portfolio.github.io pull request #3
Opened 2023-06-26 22:43 UTC by Nessrine88

Hello,

This pull request adds JavaScript functionality to the menu bar, allowing it to be toggled open and closed by clicking on a menu icon. When the menu icon is clicked, the menu list is displayed if it is currently hidden, and hidden if it is currently displayed.

Changes Made:
- Added event listener to the menu icon button
- Created JavaScript code to toggle the display of the menu list

Testing:
- Tested the functionality on different devices and browsers to ensure cross-compatibility
- Verified that the menu list opens and closes as expected
- Checked for any console errors or unexpected behavior

Please review this pull request. Thank you!

2023-06-26 22:51 UTC, Shedrack-Sunday requested changes
Hi @Nessrine88 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔴 

You have submitted a project, that is missing the `.eslintrc.json` file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-27 00:21 UTC, Shedrack-Sunday requested changes
Hello @Nessrine88 and @jovasal    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Nice work with the setup✔️  
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirement


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-27 00:21 UTC, Shedrack-Sunday commented on index.html
> +                <span id="closeIcon" class="close-icon">&times;</span>
- [ ] Kindly change the color of your close button on the menu to that provided on the template 👍 . This is to show your skills in recreating a given design 👍 

###  Figma:
![image](https://github.com/Nessrine88/Portfolio.github.io/assets/50990925/72f43ab9-13b1-434e-a8a6-2d479871b163)

### Your work:
![image](https://github.com/Nessrine88/Portfolio.github.io/assets/50990925/34a23874-c0f3-4037-99d6-25554c6d8119)

2023-06-27 00:21 UTC, Shedrack-Sunday commented on index.html
> +                    <li><a href="#contact-me"> Contact</li></a>
- [ ] From the design given, the menu covers the whole page in a white background when clicked. Kindly implement this 👍 
- [ ] Kindly adjust the margin of the navigation items to the left a little to have the same dimensions as provided on the template 

### Template given:
![image](https://github.com/Nessrine88/Portfolio.github.io/assets/50990925/bd551831-ccc6-4cb9-9bce-3602d36ff3bb)

### Your work:
![image](https://github.com/Nessrine88/Portfolio.github.io/assets/50990925/7fe758b4-320f-4ed1-84f9-83f17b17a337)

2023-06-27 13:05 UTC, usorfaitheloho requested changes
> Hi @Nessrine88  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * Great job implementing some changes requested by the previous reviewer ✔️
> * Descriptive pull request ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 13:05 UTC, usorfaitheloho commented on index.html
> +                    <li><a href="#contact-me"> Contact</li></a>
As suggested by the previous reviewer, your menu should cover the whole or entire screen in a white background. At the moment, your menu only covers a part of the screen and when you scroll down the menu part is gone .Please implement  the menu popup to be similar as it is with the design given for your Portfolio to look more presentable 😉 

Your design :

https://github.com/Nessrine88/Portfolio.github.io/assets/20537712/b45332ae-27fd-4c42-a5d5-58d6e28de4ec


Figma design :
![image](https://github.com/Nessrine88/Portfolio.github.io/assets/20537712/e59e03fb-8f94-44ab-a9de-1e7d08e3126c)

2023-06-27 13:33 UTC, Nessrine88 commented
@usorfaitheloho
I apologize for the confusion, but I'm having difficulty understanding the specific changes that are required. Could you please provide more detailed instructions or clarify the modifications needed for the menu implementation?

2023-06-27 14:08 UTC, usorfaitheloho commented
Sorry for replying now, I just saw your message. what I mean is that when a user scrolls down after clicking your mobile menu, he shouldn't see your home page but rather the menu popup background, this is what you have ⬇️ 

![image](https://github.com/Nessrine88/Portfolio.github.io/assets/20537712/1569df9a-c39d-4fe5-9ce4-00ff2ee8e9ab)

2023-06-27 16:17 UTC, topeogunleye approved these changes
### Hi @Nessrine88, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Made sure mobile menu covers the entire screen ✔️ 
 
## [Optional] suggestions:
- For future pull requests, please notice that your branch name `menu-with-js` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-menu-with-js`. This makes it easier to track the changes and the purpose of each branch. 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-27 16:24 UTC, merged